CREATE TABLE CONTACT_LENSES (
    AGE                 VARCHAR(20),
    SPECTACLE_PRESCRIP  VARCHAR(20),
    ASTIGMATISM         VARCHAR(20),
    TEAR_PROD_RATE      VARCHAR(20),
    CONTACT_LENSES      VARCHAR(20)
);

