CREATE TABLE CANDIDATES (
    AGE INTEGER,
    SEX CHAR(1),
    EDUCATION INTEGER,
    LANGUAGES INTEGER,
    EXPERIENCE INTEGER,
    PRESENTATION INTEGER,
    ASSIGNED VARCHAR(10));

INSERT INTO CANDIDATES (AGE, SEX, EDUCATION, LANGUAGES, EXPERIENCE, PRESENTATION, ASSIGNED) VALUES (25, 'M', 2, 4, 5, 2, 'NO');
INSERT INTO CANDIDATES (AGE, SEX, EDUCATION, LANGUAGES, EXPERIENCE, PRESENTATION, ASSIGNED) VALUES (23, 'W', 4, 3, 4, 2, 'NO');
INSERT INTO CANDIDATES (AGE, SEX, EDUCATION, LANGUAGES, EXPERIENCE, PRESENTATION, ASSIGNED) VALUES (21, 'M', 4, 5, 5, 4, 'YES');
INSERT INTO CANDIDATES (AGE, SEX, EDUCATION, LANGUAGES, EXPERIENCE, PRESENTATION, ASSIGNED) VALUES (29, 'M', 3, 2, 3, 1, 'NO');

CREATE TABLE TENNIS_EXAMPLE (
    PLAY_TENNIS VARCHAR(10),
    OUTLOOK VARCHAR(10),
    TEMPERATURE VARCHAR(10),
    HUMIDITY VARCHAR(10),
    WINDY VARCHAR(10));

INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('No', 'Sunny', 'Hot', 'High', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('No', 'Sunny', 'Hot', 'High', 'True');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Overcast', 'Hot', 'High', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Rainy', 'Mild', 'High', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Rainy', 'Cold', 'Normal', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('No', 'Rainy', 'Cold', 'Normal', 'True');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Overcast', 'Cold', 'Normal', 'True');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('No', 'Sunny', 'Mild', 'High', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Sunny', 'Cold', 'Normal', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Rainy', 'Mild', 'Normal', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Sunny', 'Mild', 'Normal', 'True');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Overcast', 'Mild', 'High', 'True');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('Yes', 'Overcast', 'Hot', 'Normal', 'False');
INSERT INTO TENNIS_EXAMPLE (PLAY_TENNIS, OUTLOOK, TEMPERATURE, HUMIDITY, WINDY) VALUES ('No', 'Rainy', 'Mild', 'High', 'True');

CREATE TABLE TRAINING_EXAMPLES (
    OUTCOME VARCHAR(10),
    WHERE_ VARCHAR(10),
    WHEN_ VARCHAR(10),
    FRED_STARTS INTEGER,
    JOE_OFFENSE VARCHAR(10),
    JOE_DEFENSE VARCHAR(10),
    OPP_CENTER VARCHAR(10));

INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Home', '7pm', 1, 'Center', 'Forward', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Home', '7pm', 1, 'Forward', 'Center', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Away', '7pm', 1, 'Forward', 'Forward', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Home', '5pm', 0, 'Forward', 'Center', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Away', '9pm', 1, 'Forward', 'Forward', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Away', '7pm', 0, 'Center', 'Forward', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Home', '7pm', 0, 'Forward', 'Center', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Home', '7pm', 1, 'Center', 'Center', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Away', '7pm', 1, 'Center', 'Center', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Home', '9pm', 0, 'Forward', 'Center', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Away', '7pm', 0, 'Forward', 'Forward', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Away', '5pm', 0, 'Center', 'Forward', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Home', '7pm', 0, 'Center', 'Center', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Home', '9pm', 0, 'Forward', 'Forward', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Away', '9pm', 1, 'Center', 'Forward', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Home', '7pm', 1, 'Center', 'Center', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Home', '7pm', 1, 'Center', 'Forward', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Home', '5pm', 0, 'Forward', 'Center', 'Short');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Won', 'Home', '7pm', 1, 'Center', 'Forward', 'Tall');
INSERT INTO TRAINING_EXAMPLES (OUTCOME, WHERE_, WHEN_, FRED_STARTS, JOE_OFFENSE, JOE_DEFENSE, OPP_CENTER) VALUES ('Lost', 'Away', '5pm', 0, 'Center', 'Center', 'Tall');

COMMIT WORK;