
-- TREE_NODES table
CREATE TABLE TREE_NODES (
    TRN_ID INTEGER NOT NULL,
    TRN_PARENT_NODE_ID INTEGER,
    TRN_PARENT_EDGE VARCHAR(200),
    TRN_TYPE CHAR(1) NOT NULL CHECK (TRN_TYPE = 'C' OR TRN_TYPE = 'V'),
    TRN_VALUE VARCHAR(200) NOT NULL,
    TRN_CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TRN_MODIFY_DATE TIMESTAMP DEFAULT NULL);
alter table TREE_NODES
add constraint PK_TREE_NODES
primary key (TRN_ID);
DESCRIBE FIELD TRN_ID TABLE TREE_NODES 'tree node id';
DESCRIBE FIELD TRN_PARENT_NODE_ID TABLE TREE_NODES 'parent node id, null equals root';
DESCRIBE FIELD TRN_PARENT_EDGE TABLE TREE_NODES 'edge description to parent, null for root';
DESCRIBE FIELD TRN_TYPE TABLE TREE_NODES 'C - Column name, V - value';
DESCRIBE FIELD TRN_VALUE TABLE TREE_NODES 'node value';
DESCRIBE FIELD TRN_CREATE_DATE TABLE TREE_NODES 'audit create date';
DESCRIBE FIELD TRN_MODIFY_DATE TABLE TREE_NODES 'audit modify date';
CREATE GENERATOR GEN_TREE_NODES_ID;
SET GENERATOR GEN_TREE_NODES_ID TO 1;

-- Forreing self key 
alter table TREE_NODES
add constraint FK_SELF_TRN_ID
foreign key (TRN_PARENT_NODE_ID)
references TREE_NODES(TRN_ID)

-- TREE_DATA_SOURCES

CREATE TABLE TREE_DATA_SOURCES (
    TDS_ID INTEGER NOT NULL,
    TDS_NAME VARCHAR(50) NOT NULL,
    TDS_SOLUTION_ID INTEGER NOT NULL,
    TDS_TABLE VARCHAR(50) NOT NULL,
    TDS_DECISIONED_COLUMN VARCHAR(50) NOT NULL,
    TDS_DECISIONING_COLUMNS VARCHAR(4000) NOT NULL,
    TDS_CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TDS_MODIFY_DATE TIMESTAMP DEFAULT NULL);
alter table TREE_DATA_SOURCES
add constraint PK_TREE_DATA_SOURCES
primary key (TDS_ID);
DESCRIBE FIELD TDS_ID TABLE TREE_DATA_SOURCES 'data source id';
DESCRIBE FIELD TDS_NAME TABLE TREE_DATA_SOURCES 'data source name';
DESCRIBE FIELD TDS_SOLUTION_ID TABLE TREE_DATA_SOURCES 'sollution id, needed for database login entry';
DESCRIBE FIELD TDS_TABLE TABLE TREE_DATA_SOURCES 'table contains data';
DESCRIBE FIELD TDS_DECISIONED_COLUMN TABLE TREE_DATA_SOURCES 'column which is subject of decisioning';
DESCRIBE FIELD TDS_DECISIONING_COLUMNS TABLE TREE_DATA_SOURCES 'columns which are symptomes';
DESCRIBE FIELD TDS_CREATE_DATE TABLE TREE_DATA_SOURCES 'audit create date';
DESCRIBE FIELD TDS_MODIFY_DATE TABLE TREE_DATA_SOURCES 'audit modify date';
CREATE GENERATOR GEN_TREE_DATA_SOURCES_ID;
SET GENERATOR GEN_TREE_DATA_SOURCES_ID TO 1;

-- Foreign key for TREE_DATA_SOURCES
alter table TREE_DATA_SOURCES
add constraint FK_TREE_DS_SOLUTION_ID
foreign key (TDS_SOLUTION_ID)
references SOLUTIONS(SOLUTION_ID);


-- TREES

CREATE TABLE TREES (
    TRE_ID INTEGER NOT NULL,
    TRE_NAME VARCHAR(50) NOT NULL,
    TRE_INFO VARCHAR(200),
    TRE_TASK_ID INTEGER NOT NULL,
    TRE_TDS_ID INTEGER NOT NULL,
    TRE_TRN_ID INTEGER NOT NULL,
    TRE_CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TRE_MODIFY_DATE TIMESTAMP DEFAULT NULL);
alter table TREES
add constraint PK_TREES
primary key (TRE_ID);
DESCRIBE FIELD TRE_ID TABLE TREES 'tree id';
DESCRIBE FIELD TRE_NAME TABLE TREES 'tree name';
DESCRIBE FIELD TRE_INFO TABLE TREES 'tree info';
DESCRIBE FIELD TRE_TASK_ID TABLE TREES 'task id, describing plugin and project parameters';
DESCRIBE FIELD TRE_TDS_ID TABLE TREES 'data source id';
DESCRIBE FIELD TRE_TRN_ID TABLE TREES 'root node id';
DESCRIBE FIELD TRE_CREATE_DATE TABLE TREES 'audit create date';
DESCRIBE FIELD TRE_MODIFY_DATE TABLE TREES 'audit modify date';
CREATE GENERATOR GEN_TREES_ID;
SET GENERATOR GEN_TREES_ID TO 1;


-- Foreign keys for TREES
alter table TREES
add constraint FK_TREES_TASK_ID
foreign key (TRE_TASK_ID)
references TASKS(TASK_ID);

alter table TREES
add constraint FK_TREES_TDS_ID
foreign key (TRE_TDS_ID)
references TREE_DATA_SOURCES(TDS_ID);

alter table TREES
add constraint FK_TREES_TRN_ID
foreign key (TRE_TRN_ID)
references TREE_NODES(TRN_ID);

