CREATE TABLE PERSONS (
    ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20));

alter table PERSONS
add constraint PK_PERSONS
primary key (ID);

CREATE GENERATOR GEN_PERSONS_ID;
